from colorama import Fore, Style, Back
import colorama

colorama.init()

print(Back.WHITE)
print(Fore.BLACK + ' чёрный текст')
print(Style.BRIGHT + ' стал ярче')
print(Back.BLACK)
print(Style.NORMAL)
print('\n')
print(Fore.RED + ' красный текст')
print(Style.BRIGHT + ' стал ярче')
print('\n')
print(Style.NORMAL)
print(Fore.GREEN + ' зелёный текст')
print(Style.BRIGHT + ' стал ярче')
print('\n')
print(Style.NORMAL)
print(Fore.YELLOW + ' жёлтый текст')
print(Style.BRIGHT + ' стал ярче')
print('\n')
print(Style.NORMAL)
print(Fore.BLUE + ' синий текст')
print(Style.BRIGHT + ' стал ярче')
print('\n')
print(Style.NORMAL)
print(Fore.MAGENTA + ' розовый текст')
print(Style.BRIGHT + ' стал ярче')
print('\n')
print(Style.NORMAL)
print(Fore.CYAN + ' циановый текст')
print(Style.BRIGHT + ' стал ярче')
print('\n')
print(Fore.WHITE + ' белый текст')
print(Style.BRIGHT + ' стал ярче')
print('\n')
print(Style.RESET_ALL)
print(' обычный текст')